### ISSUE TITLE
cod function anticipates non-empty vector

### ISSUE THREAD

**Issue by rross0** [ccao-data/assessr#8]
I have a set of ratios, and I group them and try to calculate CODs using dplyr's summarise() function.  Some groups are empty. I get the error:

```
Error in `dplyr::summarise()`:
ℹ In argument: `cod = assessr::cod(ratio)`.
ℹ In group 101: `year = 2016`, `triad_name = "North"`, `stage = "Certified by Assessor"`, `sale = "Year following
  reassessment year"`.
Caused by error in `FUN()`:
! length(x) > 1 is not TRUE
```

It may be better to return an `NA` value for groups that don't have any observations.

**Comment by dfsnow** [comment]
All the other functions in this package use the same check, which we implemented because we felt it was better to return an error than unexpectedly return `NaN` or `NA`.

If you want to return `NA` for length 0 vectors, just add a wrapper around the call to `cod()`. Something like:

```r
df %>%
  group_by(township) %>%
  summarize(
    cod = ifelse(sum(!is.na(ratio)) > 0, cod(ratio), NA_real_),
  )
```
